openapi: 3.0.0
info:
  version: 0.0.1
  title: Retail API Service (U2 Capstone)
  description: Database-backed REST web microservice that enables users to search for and purchase products
  
servers: 
  - url: http://localhost:8181
    description: Local dev server
    
paths:
  /invoices:
    post:
      summary: Create a new purchase
      description: Creates new purchase object with existing customer Id or new Customer object
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PurchasePost'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PurchaseResponse'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: string
        '404':
          description: Not found
          content:
            application/json:
              schema:
                type: string
                
    get:
      summary: Get all invoices
      description: Get list of all invoices in DB
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvoiceResponseList'
                
  /invoices/{id}:
    get:
      summary: Get invoice by id
      description: Queries for invoice by id
      parameters: 
        - name: id
          in: path
          required: true
          description: Invoice id
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvoiceResponse'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: string
        '404':
          description: Not found
          content:
            application/json:
              schema:
                type: string
                
  /invoices/customer/{customer_id}:
    get:
      summary: Get invoices by customer id
      description: Queries for invoices by customer id
      parameters: 
        - name: customer_id
          in: path
          required: true
          description: Customer id
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/InvoiceResponse'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: string
        '404':
          description: Not found
          content:
            application/json:
              schema:
                type: string

  /products/{id}:
    get:
      summary: Get product by id
      description: Queries for product by id
      parameters: 
        - name: id
          in: path
          required: true
          description: Product id
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: string
        '404':
          description: Not found
          content:
            application/json:
              schema:
                type: string
                
  /products/inventory:
    get:
      summary: Get a list of products currently in inventory
      description: Get products in inventory
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponseList'
                
  /products/invoice/{invoice_id}:
    get:
      summary: Get list of products by invoice id
      description: Get list of products on an invoice by invoice id
      parameters: 
        - name: invoice_id
          in: path
          required: true
          description: Invoice id
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponseList'
  
  /levelup/customer/{customer_id}:
    get:
      summary: Get levelup points by customer id
      description: get customer total levelup points by customer id in path
      parameters:
        - name: customer_id
          in: path
          required: true
          description: Customer id
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: number
        '404':
          description: Not found
          content:
            application/json:
              schema:
                type: string

components:
  schemas:

    PurchasePost:
      type: object
      properties:
        customerId:
          type: number
        customer:
          $ref: '#/components/schemas/CustomerPost'
        purchaseDate:
          type: string  
        inventoryList:
          type: array
          items:
            $ref: '#/components/schemas/PurchaseItem'
      required:
      - purchaseDate
      - inventoryList
      
    PurchaseResponse:
      type: object
      properties:
        Invoice:
          type: object
          properties:
            invoiceId:
              type: number
            customerId:
              type: number
            purchaseDate:
              type: string
        customer:
          $ref: '#/components/schemas/CustomerResponse'
        productList:
          type: array
          items:
            $ref: '#/components/schemas/ProductView'
        lvlUpPtsThisPurchase:
          type: number
        totalLvlUpPts:
          type: string
        totalPrice:
          type: number
          
    CustomerResponse:
      type: object
      properties:
        customer_id:
          type: number
        first_name:
          type: string
        last_name:
          type: string
        street:
          type: string
        city:
          type: string
        zip:
          type: string
        email:
          type: string
        phone:
          type: string
          
    PurchaseItem:
      properties:
        inventoryId:
          type: number
        quantity:
          type: number
      required:
      - inventoryId
      - quantity
          
    CustomerPost:
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
        street:
          type: string
        city:
          type: string
        zip:
          type: string
        email:
          type: string
        phone:
          type: string
      required: 
      - first_name
      - last_name
      - street
      - city
      - zip
      - email
      - phone
          
    ProductResponse:
      type: object
      properties:
        product_id:
          type: number
        product_name:
          type: string
        product_description:
          type: string
        list_price:
          type: number
        unit_cost:
          type: number
          
    ProductView:
      type: object
      properties:
        productName:
          type: string
        productDescription:
          type: string
        quantity:
          type: number
        listPrice:
          type: number
        productTotal:
          type: number
          
    ProductResponseList:
      type: array
      items:
        $ref: '#/components/schemas/ProductResponse'

    InvoicePostItem:
      type: object
      properties:
        inventory_id:
          type: number
        quantity:
          type: number
      required:
      - inventory_id
      - quantity

    InvoiceResponse:
      type: object
      properties:
        invoiceId:
          type: number
        customerId:
          type: number
        purchaseDate:
          type: string
        invoiceItemList:
          type: array
          items:
            $ref: '#/components/schemas/InvoicePostItem'
            
    InvoiceResponseList:
      type: array
      items:
        $ref: '#/components/schemas/InvoiceResponse'
        
        